name: Deno Deploy
on:
  push:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - uses: actions/checkout@v3
      - run: corepack enable
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm

      - run: pnpm install
      - run: pnpm build:deno

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "nitro-starter"
          entrypoint: server/index.ts
          root: .output
